exclude: |
  (?x)(
      ^foo_ui_columns/resource.h|
      .rc|
      .vcxproj|
      .vcxproj.filters
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.1
    hooks:
      - id: prettier
        types_or: [json, markdown, yaml]
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v13.0.1
    hooks:
      - id: clang-format
        types_or: [c++]
